### ISSUE TITLE
Added some charts to my copy; might be useful to have them in there to start

### ISSUE THREAD

**Issue by sirioaklander** [joshzelonis/CarbanakFin7Eval#1]
![image](https://user-images.githubusercontent.com/2086121/115584771-e74c0f80-a27f-11eb-9c42-71fedf56e034.png)

Simple charts (this is the fin7eval.xlsx version) make the data much more readable at a glance. Attached files so you can use if desired.
[fin7eval-strict-mitre (1).xlsx](https://github.com/joshzelonis/CarbanakFin7Eval/files/6352330/fin7eval-strict-mitre.1.xlsx)
[fin7eval (1).xlsx](https://github.com/joshzelonis/CarbanakFin7Eval/files/6352331/fin7eval.1.xlsx)

**Comment by joshzelonis** [comment]
I appreciate your submitting this, but I've worked really hard over the last few years not to declare a winner but to help people understand how to interpret the data themselves. Years as a Wave author has taught me that if you throw up a graphic like this, it's all people look at, and this doesn't factor in protection capabilities which I think is just as important.

**Comment by sirioaklander** [comment]
Thanks for the response and my apologies for my over eagerness. I
immediately wanted to visualize and after my first instinct to share
realized you left that out on purpose. But I couldn't go delete my feedback.

Also, thanks for the easy analysis!

And yeah, I have been thinking since how to factor in protection
capabilities into such a visualization.

Best,

Siri
